// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Auction.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AuctionEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("AuctionStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocAttachmentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DocDate")
                        .HasColumnType("date");

                    b.Property<string>("DocNoYearly")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBidPriceHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsForwardAuction")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OpenToAll")
                        .HasColumnType("boolean");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("StatusId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("Core.Entities.Auction.AuctionRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<long?>("DocumentAttachmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("TechnicalSpecification")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UnitId");

                    b.ToTable("AuctionRequirements");
                });

            modelBuilder.Entity("Core.Entities.Auction.AuctionStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<long>("BidId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean");

                    b.Property<short>("Rank")
                        .HasColumnType("smallint");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId")
                        .IsUnique();

                    b.HasIndex("BidId");

                    b.HasIndex("VendorId");

                    b.ToTable("AuctionStatements");
                });

            modelBuilder.Entity("Core.Entities.Auction.Bid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BasicAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<short>("BidRevisionNo")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<long>("MainBidId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("MainBidId");

                    b.HasIndex("VendorId");

                    b.ToTable("Bid", "AuctionRel");
                });

            modelBuilder.Entity("Core.Entities.Auction.BidDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AuctionRequirementId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("BidId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionRequirementId");

                    b.HasIndex("BidId");

                    b.ToTable("BidDetail", "AuctionRel");
                });

            modelBuilder.Entity("Core.Entities.Auction.BidTaxDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BidDetailId")
                        .HasColumnType("bigint");

                    b.Property<short>("ChargeTypeId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("TaxId")
                        .HasColumnType("integer");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("TaxNatureId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("TaxValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BidDetailId");

                    b.HasIndex("ChargeTypeId");

                    b.HasIndex("TaxId");

                    b.HasIndex("TaxNatureId");

                    b.ToTable("BidTaxDetail", "AuctionRel");
                });

            modelBuilder.Entity("Core.Entities.Auction.VendorIntent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInterested")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQualified")
                        .HasColumnType("boolean");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorIntents");
                });

            modelBuilder.Entity("Core.Entities.Authentication.LoginAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("FailedLoginAttemptCount")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("LastAttemptedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusId")
                        .IsUnique();

                    b.ToTable("LoginAttempt", "Auth");
                });

            modelBuilder.Entity("Core.Entities.GlobalData.Category", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Category", "GlobalData");
                });

            modelBuilder.Entity("Core.Entities.GlobalData.ChargeType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ChargeType", "GlobalData");
                });

            modelBuilder.Entity("Core.Entities.GlobalData.RatingFor", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("For")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("RatingFor", "GlobalData");
                });

            modelBuilder.Entity("Core.Entities.GlobalData.RatingParameter", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RatingFor")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("RatingParameter", "GlobalData");
                });

            modelBuilder.Entity("Core.Entities.GlobalData.Status", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Status", "GlobalData");
                });

            modelBuilder.Entity("Core.Entities.GlobalData.TaxNature", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TaxNature", "GlobalData");
                });

            modelBuilder.Entity("Core.Entities.Master.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DocAttachmentId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<string>("StatusRemarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Core.Entities.Master.ItemUnitMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemUnitMappings");
                });

            modelBuilder.Entity("Core.Entities.Master.TaxMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("ChargeTypeId")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<string>("StatusRemarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("TaxNatureId")
                        .HasColumnType("smallint");

                    b.Property<decimal>("TaxValue")
                        .HasColumnType("numeric");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChargeTypeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TaxNatureId");

                    b.ToTable("TaxMasters");
                });

            modelBuilder.Entity("Core.Entities.Master.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<string>("StatusRemarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Core.Entities.TenantRelated.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int?>("ForegroundImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficialAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Organization", "Tenant");
                });

            modelBuilder.Entity("Core.Entities.TenantRelated.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVendor")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Tenant", "Tenant");
                });

            modelBuilder.Entity("Core.Entities.TenantRelated.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<int?>("ForegroundImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Vendor", "Tenant");
                });

            modelBuilder.Entity("Core.Entities.Utilities.Rating", b =>
                {
                    b.Property<short>("RatingForId")
                        .HasColumnType("smallint");

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<int>("AgainstTenant")
                        .HasColumnType("integer");

                    b.Property<int>("SubmittedByTenant")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.HasKey("RatingForId", "AuctionId", "AgainstTenant", "SubmittedByTenant");

                    b.HasIndex("AgainstTenant");

                    b.HasIndex("AuctionId");

                    b.HasIndex("SubmittedByTenant");

                    b.ToTable("Rating", "Utilities");
                });

            modelBuilder.Entity("Core.Entities.Utilities.RatingValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("RatingAgainstTenant")
                        .HasColumnType("integer");

                    b.Property<int?>("RatingAuctionId")
                        .HasColumnType("integer");

                    b.Property<short?>("RatingForId")
                        .HasColumnType("smallint");

                    b.Property<short>("RatingParameterId")
                        .HasColumnType("smallint");

                    b.Property<short>("RatingScore")
                        .HasColumnType("smallint");

                    b.Property<int?>("RatingSubmittedByTenant")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RatingParameterId");

                    b.HasIndex("RatingForId", "RatingAuctionId", "RatingAgainstTenant", "RatingSubmittedByTenant");

                    b.ToTable("RatingValue", "Utilities");
                });

            modelBuilder.Entity("Core.Entities.Auction.Auction", b =>
                {
                    b.HasOne("Core.Entities.TenantRelated.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.GlobalData.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Core.Entities.Auction.AuctionRequirement", b =>
                {
                    b.HasOne("Core.Entities.Auction.Auction", "Auction")
                        .WithMany("AuctionRequirements")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Master.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Master.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Item");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Core.Entities.Auction.AuctionStatement", b =>
                {
                    b.HasOne("Core.Entities.Auction.Auction", "Auction")
                        .WithOne("AuctionStatement")
                        .HasForeignKey("Core.Entities.Auction.AuctionStatement", "AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Auction.Bid", "Bid")
                        .WithMany()
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.TenantRelated.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Bid");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Core.Entities.Auction.Bid", b =>
                {
                    b.HasOne("Core.Entities.Auction.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Bid_AuctionId");

                    b.HasOne("Core.Entities.Auction.Bid", "MainBid")
                        .WithMany()
                        .HasForeignKey("MainBidId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Bid_MainBidId");

                    b.HasOne("Core.Entities.TenantRelated.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Bid_VendorId");

                    b.Navigation("Auction");

                    b.Navigation("MainBid");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Core.Entities.Auction.BidDetail", b =>
                {
                    b.HasOne("Core.Entities.Auction.AuctionRequirement", "AuctionRequirement")
                        .WithMany()
                        .HasForeignKey("AuctionRequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_BidDetail_AuctionRequirementId");

                    b.HasOne("Core.Entities.Auction.Bid", null)
                        .WithMany("BidDetails")
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BidDetail_BidId");

                    b.Navigation("AuctionRequirement");
                });

            modelBuilder.Entity("Core.Entities.Auction.BidTaxDetail", b =>
                {
                    b.HasOne("Core.Entities.Auction.BidDetail", "BidDetail")
                        .WithMany("Taxes")
                        .HasForeignKey("BidDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BidTaxDetail_BidDetailId");

                    b.HasOne("Core.Entities.GlobalData.ChargeType", "ChargeType")
                        .WithMany()
                        .HasForeignKey("ChargeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_BidTaxDetail_ChargeTypeId");

                    b.HasOne("Core.Entities.Master.TaxMaster", "Tax")
                        .WithMany()
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_BidTaxDetail_TaxId");

                    b.HasOne("Core.Entities.GlobalData.TaxNature", "TaxNature")
                        .WithMany()
                        .HasForeignKey("TaxNatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_BidTaxDetail_TaxNatureId");

                    b.Navigation("BidDetail");

                    b.Navigation("ChargeType");

                    b.Navigation("Tax");

                    b.Navigation("TaxNature");
                });

            modelBuilder.Entity("Core.Entities.Auction.VendorIntent", b =>
                {
                    b.HasOne("Core.Entities.Auction.Auction", "Auction")
                        .WithMany("VendorIntent")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.TenantRelated.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Core.Entities.Authentication.LoginAttempt", b =>
                {
                    b.HasOne("Core.Entities.GlobalData.Status", "Status")
                        .WithOne()
                        .HasForeignKey("Core.Entities.Authentication.LoginAttempt", "StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Fk_LoginAttempt_StatusId");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Core.Entities.Master.Item", b =>
                {
                    b.HasOne("Core.Entities.GlobalData.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Entities.Master.ItemUnitMapping", b =>
                {
                    b.HasOne("Core.Entities.Master.Item", null)
                        .WithMany("ApplicableUnits")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Master.TaxMaster", b =>
                {
                    b.HasOne("Core.Entities.GlobalData.ChargeType", "ChargeType")
                        .WithMany()
                        .HasForeignKey("ChargeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.GlobalData.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.GlobalData.TaxNature", "TaxNature")
                        .WithMany()
                        .HasForeignKey("TaxNatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargeType");

                    b.Navigation("Status");

                    b.Navigation("TaxNature");
                });

            modelBuilder.Entity("Core.Entities.TenantRelated.Organization", b =>
                {
                    b.HasOne("Core.Entities.TenantRelated.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Organization_TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Core.Entities.TenantRelated.Vendor", b =>
                {
                    b.HasOne("Core.Entities.TenantRelated.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Organization_TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Core.Entities.Utilities.Rating", b =>
                {
                    b.HasOne("Core.Entities.TenantRelated.Tenant", null)
                        .WithMany()
                        .HasForeignKey("AgainstTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Rating_AgainstTenant");

                    b.HasOne("Core.Entities.Auction.Auction", null)
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Rating_AuctionId");

                    b.HasOne("Core.Entities.TenantRelated.Tenant", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Rating_SubmittedByTenant");
                });

            modelBuilder.Entity("Core.Entities.Utilities.RatingValue", b =>
                {
                    b.HasOne("Core.Entities.GlobalData.RatingParameter", "RatingParameter")
                        .WithMany()
                        .HasForeignKey("RatingParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RatingValue_RatingParameterId");

                    b.HasOne("Core.Entities.Utilities.Rating", null)
                        .WithMany("RatingValues")
                        .HasForeignKey("RatingForId", "RatingAuctionId", "RatingAgainstTenant", "RatingSubmittedByTenant");

                    b.Navigation("RatingParameter");
                });

            modelBuilder.Entity("Core.Entities.Auction.Auction", b =>
                {
                    b.Navigation("AuctionRequirements");

                    b.Navigation("AuctionStatement")
                        .IsRequired();

                    b.Navigation("Bids");

                    b.Navigation("VendorIntent");
                });

            modelBuilder.Entity("Core.Entities.Auction.Bid", b =>
                {
                    b.Navigation("BidDetails");
                });

            modelBuilder.Entity("Core.Entities.Auction.BidDetail", b =>
                {
                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("Core.Entities.Master.Item", b =>
                {
                    b.Navigation("ApplicableUnits");
                });

            modelBuilder.Entity("Core.Entities.Utilities.Rating", b =>
                {
                    b.Navigation("RatingValues");
                });
#pragma warning restore 612, 618
        }
    }
}
