-- BidNexus GlobalData Seed
-- Target branch baseline: Develop
-- Purpose: application-wide reference data required by GlobalData and TaxMaster.
-- Safe to execute repeatedly: rows are upserted by their stable seed IDs.
--
-- IMPORTANT:
-- 1. These IDs are intentionally stable because tenant/master records may reference them.
-- 2. Do not renumber existing seed IDs after deployment.
-- 3. This script does not insert tenant-specific Master data.

BEGIN;

-- ------------------------------------------------------------
-- Category
-- ------------------------------------------------------------
INSERT INTO "GlobalData"."Category" ("Id", "Name", "Code")
VALUES
    (1, 'Steel',        'STEEL'),
    (2, 'Machinery',    'MACH'),
    (3, 'Electrical',   'ELEC'),
    (4, 'Consumables',  'CONS'),
    (5, 'Services',     'SERV')
ON CONFLICT ("Id") DO UPDATE
SET
    "Name" = EXCLUDED."Name",
    "Code" = EXCLUDED."Code";

-- ------------------------------------------------------------
-- Status
-- Generic application/master/auction lifecycle statuses.
-- ------------------------------------------------------------
INSERT INTO "GlobalData"."Status" ("Id", "Name", "Inactive")
VALUES
    (1, 'Active',     FALSE),
    (2, 'Inactive',   TRUE),
    (3, 'Draft',      FALSE),
    (4, 'Pending',    FALSE),
    (5, 'Approved',   FALSE),
    (6, 'Rejected',   FALSE),
    (7, 'Open',       FALSE),
    (8, 'Closed',     FALSE),
    (9, 'Completed',  FALSE),
    (10, 'Cancelled', TRUE)
ON CONFLICT ("Id") DO UPDATE
SET
    "Name" = EXCLUDED."Name",
    "Inactive" = EXCLUDED."Inactive";

-- ------------------------------------------------------------
-- RatingFor
-- Entities that can be the subject of a rating.
-- ------------------------------------------------------------
INSERT INTO "GlobalData"."RatingFor" ("Id", "For", "Inactive")
VALUES
    (1, 'Vendor',       FALSE),
    (2, 'Organization', FALSE),
    (3, 'Auction',      FALSE)
ON CONFLICT ("Id") DO UPDATE
SET
    "For" = EXCLUDED."For",
    "Inactive" = EXCLUDED."Inactive";

-- ------------------------------------------------------------
-- RatingParameter
-- Standard rating dimensions.
--
-- RatingFor is retained exactly as modeled by the current domain:
-- boolean flag, not a foreign key to RatingFor.
-- ------------------------------------------------------------
INSERT INTO "GlobalData"."RatingParameter"
    ("Id", "ParameterName", "RatingFor", "Inactive")
VALUES
    (1, 'Quality',       TRUE,  FALSE),
    (2, 'Delivery',      TRUE,  FALSE),
    (3, 'Responsiveness',TRUE,  FALSE),
    (4, 'Commercial',    FALSE, FALSE)
ON CONFLICT ("Id") DO UPDATE
SET
    "ParameterName" = EXCLUDED."ParameterName",
    "RatingFor" = EXCLUDED."RatingFor",
    "Inactive" = EXCLUDED."Inactive";

-- ------------------------------------------------------------
-- TaxNature
-- Describes the nature/type of a tax or statutory charge.
-- ------------------------------------------------------------
INSERT INTO "GlobalData"."TaxNature" ("Id", "Name", "Code", "IsActive")
VALUES
    (1, 'GST',  'GST',  TRUE),
    (2, 'IGST', 'IGST', TRUE),
    (3, 'CGST', 'CGST', TRUE),
    (4, 'SGST', 'SGST', TRUE),
    (5, 'Cess', 'CESS', TRUE)
ON CONFLICT ("Id") DO UPDATE
SET
    "Name" = EXCLUDED."Name",
    "Code" = EXCLUDED."Code",
    "IsActive" = EXCLUDED."IsActive";

-- ------------------------------------------------------------
-- ChargeType
-- Defines how a tax/charge value is interpreted.
-- ------------------------------------------------------------
INSERT INTO "GlobalData"."ChargeType" ("Id", "Name", "Code", "IsActive")
VALUES
    (1, 'Percentage', 'PERCENTAGE', TRUE),
    (2, 'Fixed',      'FIXED',      TRUE)
ON CONFLICT ("Id") DO UPDATE
SET
    "Name" = EXCLUDED."Name",
    "Code" = EXCLUDED."Code",
    "IsActive" = EXCLUDED."IsActive";

-- ------------------------------------------------------------
-- Synchronize PostgreSQL-generated ID sequences after explicit IDs.
-- Works for the serial/identity sequences generated by EF Core.
-- ------------------------------------------------------------
SELECT setval(
    pg_get_serial_sequence('"GlobalData"."Category"', 'Id'),
    COALESCE((SELECT MAX("Id") FROM "GlobalData"."Category"), 1),
    TRUE
);

SELECT setval(
    pg_get_serial_sequence('"GlobalData"."Status"', 'Id'),
    COALESCE((SELECT MAX("Id") FROM "GlobalData"."Status"), 1),
    TRUE
);

SELECT setval(
    pg_get_serial_sequence('"GlobalData"."RatingFor"', 'Id'),
    COALESCE((SELECT MAX("Id") FROM "GlobalData"."RatingFor"), 1),
    TRUE
);

SELECT setval(
    pg_get_serial_sequence('"GlobalData"."RatingParameter"', 'Id'),
    COALESCE((SELECT MAX("Id") FROM "GlobalData"."RatingParameter"), 1),
    TRUE
);

SELECT setval(
    pg_get_serial_sequence('"GlobalData"."TaxNature"', 'Id'),
    COALESCE((SELECT MAX("Id") FROM "GlobalData"."TaxNature"), 1),
    TRUE
);

SELECT setval(
    pg_get_serial_sequence('"GlobalData"."ChargeType"', 'Id'),
    COALESCE((SELECT MAX("Id") FROM "GlobalData"."ChargeType"), 1),
    TRUE
);

COMMIT;
